<?php

use App\Models\Installment;
use App\Models\Payment;
use App\Models\PaymentAllocation;
use App\Models\Plot;
use App\Models\Receipt;
use App\Models\Subscription;
use Illuminate\Database\QueryException;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

uses(RefreshDatabase::class);

test('phase one creates every domain table with the required storage settings', function () {
    $tables = [
        'roles', 'permissions', 'user_roles', 'role_permissions', 'customers', 'customer_documents',
        'neighborhoods', 'avenues', 'plots', 'payment_plans', 'subscriptions', 'contracts',
        'installments', 'payments', 'payment_allocations', 'receipts', 'audit_logs', 'settings',
    ];

    foreach ($tables as $table) {
        expect(Schema::hasTable($table))->toBeTrue();
    }

    $tableOptions = collect(DB::select(
        'SELECT TABLE_NAME, ENGINE, TABLE_COLLATION FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME IN ('.implode(',', array_fill(0, count($tables), '?')).')',
        $tables,
    ))->keyBy('TABLE_NAME');

    expect($tableOptions)->toHaveCount(count($tables));

    foreach ($tables as $table) {
        expect(strtolower($tableOptions[$table]->ENGINE))->toBe('innodb')
            ->and(strtolower($tableOptions[$table]->TABLE_COLLATION))->toStartWith('utf8mb4');
    }
});

test('calculated balances are generated by MySQL', function () {
    $subscription = Subscription::factory()->create(['contract_total' => '3600.00']);
    DB::table('subscriptions')->where('id', $subscription->id)->update(['amount_paid' => '600.00']);
    $subscription->refresh();
    $installment = Installment::factory()->for($subscription)->create([
        'amount_due' => '300.00',
        'amount_paid' => '125.00',
    ])->refresh();

    expect($subscription->balance)->toBe('3000.00')
        ->and($installment->balance)->toBe('175.00');
});

test('a plot cannot have two concurrent subscriptions', function () {
    $plot = Plot::factory()->create();

    Subscription::factory()->for($plot)->create(['commercial_status' => 'active']);

    expect(fn () => Subscription::factory()->for($plot)->create(['commercial_status' => 'pending']))
        ->toThrow(QueryException::class);

    Subscription::factory()->for($plot)->create(['commercial_status' => 'cancelled']);

    expect(Subscription::query()->where('plot_id', $plot->id)->count())->toBe(2);
});

test('financial tables reject invalid amounts and duplicate allocations', function () {
    $subscription = Subscription::factory()->create();
    $installment = Installment::factory()->for($subscription)->create();
    $payment = Payment::factory()->for($subscription)->create([
        'customer_id' => $subscription->customer_id,
    ]);

    expect(fn () => Payment::factory()->for($subscription)->create([
        'customer_id' => $subscription->customer_id,
        'amount' => '0.00',
    ]))->toThrow(QueryException::class);

    PaymentAllocation::factory()->create([
        'payment_id' => $payment->id,
        'installment_id' => $installment->id,
    ]);

    expect(fn () => PaymentAllocation::factory()->create([
        'payment_id' => $payment->id,
        'installment_id' => $installment->id,
    ]))->toThrow(QueryException::class);
});

test('a payment has at most one receipt', function () {
    $subscription = Subscription::factory()->create();
    $payment = Payment::factory()->for($subscription)->create([
        'customer_id' => $subscription->customer_id,
    ]);

    Receipt::factory()->for($payment)->create([
        'customer_id' => $subscription->customer_id,
        'subscription_id' => $subscription->id,
        'amount' => $payment->amount,
    ]);

    expect(fn () => Receipt::factory()->for($payment)->create([
        'customer_id' => $subscription->customer_id,
        'subscription_id' => $subscription->id,
        'amount' => $payment->amount,
    ]))->toThrow(QueryException::class);
});
