<x-layouts.app :title="$subscription->subscription_number">
    <div class="customer-record portal-page">
        <header class="record-heading">
            <div><p class="app-kicker">{{ __('portal.contract_file') }}</p><h1>{{ $subscription->subscription_number }}</h1><p>{{ $subscription->plot->reference }} · {{ $subscription->plot->avenue->neighborhood->name }}</p></div>
            <div class="resource-heading__actions"><a href="{{ route('portal.subscriptions.index') }}" class="btn btn-outline"><i class="bi bi-arrow-left" aria-hidden="true"></i>{{ __("Mes souscriptions") }}</a><span class="status-badge status-badge--{{ $subscription->commercial_status === 'active' ? 'active' : 'neutral' }}">{{ __('statuses.'.$subscription->commercial_status) }}</span></div>
        </header>

        <section class="detail-sheet"><div class="detail-sheet__section"><div class="detail-sheet__header"><h2>{{ __('portal.contract_information') }}</h2><span>{{ __('portal.reference') }} {{ $subscription->subscription_number }}</span></div><dl class="detail-grid">
            <div><dt>{{ __('portal.plot') }}</dt><dd>{{ $subscription->plot->reference }}</dd></div><div><dt>{{ __('portal.location') }}</dt><dd>{{ $subscription->plot->avenue->name }}, {{ $subscription->plot->avenue->neighborhood->name }}</dd></div><div><dt>{{ __('portal.plan') }}</dt><dd>{{ $subscription->paymentPlan->name }}</dd></div><div><dt>{{ __('portal.contract_total') }}</dt><dd class="record-money">{{ number_format((float) $subscription->contract_total, 2, ',', ' ') }} USD</dd></div><div><dt>{{ __('portal.amount_paid') }}</dt><dd class="record-money text-success">{{ number_format((float) $subscription->amount_paid, 2, ',', ' ') }} USD</dd></div><div><dt>{{ __('portal.remaining_balance') }}</dt><dd class="record-money">{{ number_format((float) $subscription->balance, 2, ',', ' ') }} USD</dd></div>
        </dl></div></section>

        <section class="resource-table"><div class="resource-table__header"><div><h2>{{ __('portal.installment_schedule') }}</h2><p>{{ trans_choice('portal.installment_count', $subscription->installments->count()) }}</p></div></div><div class="table-responsive"><table class="table resource-data-table portal-data-table"><thead><tr><th>{{ __('portal.number') }}</th><th>{{ __('portal.date') }}</th><th class="text-end">{{ __('portal.amount_due') }}</th><th class="text-end">{{ __('portal.paid') }}</th><th class="text-end">{{ __('portal.balance') }}</th><th>{{ __("Statut") }}</th></tr></thead><tbody>
            @forelse($subscription->installments as $installment)<tr class="{{ $installment->status === 'overdue' ? 'resource-data-table__row--attention' : '' }}"><td>{{ $installment->installment_number }}</td><td>{{ $installment->due_date->format('d/m/Y') }}</td><td class="record-money text-end">{{ number_format((float) $installment->amount_due, 2, ',', ' ') }} USD</td><td class="record-money text-end">{{ number_format((float) $installment->amount_paid, 2, ',', ' ') }} USD</td><td class="record-money text-end">{{ number_format((float) $installment->balance, 2, ',', ' ') }} USD</td><td><span class="status-badge status-badge--{{ in_array($installment->status, ['paid', 'settled']) ? 'active' : ($installment->status === 'overdue' ? 'danger' : 'neutral') }}">{{ __('statuses.'.$installment->status) }}</span></td></tr>
            @empty<tr><td colspan="6"><div class="resource-empty"><strong>{{ __('portal.none') }} {{ __('portal.installment') }}</strong><span>{{ __('portal.schedule_not_generated') }}</span></div></td></tr>@endforelse
        </tbody></table></div></section>
    </div>
</x-layouts.app>
